stages:
  build:
    cmd: export VOCAB_PATH=outputs/vocab.plk MODEL_PATH=outputs/checkpoint.pth CONFIG_PATH=outputs/config.json
      RESULTS_PATH=outputs/results.json SUBMISSION_PATH=outputs/submission.csv
    always_changed: true
  prepare:
    cmd: python prepare.py
    deps:
    - data/train.csv
    params:
    - basic
    outs:
    - outputs/vocab.plk
  train:
    cmd: python train.py
    deps:
    - data/train.csv
    - outputs/vocab.plk
    - train.py
    params:
    - model
    - train
    outs:
    - outputs/checkpoint.pth
    - outputs/config.json
    metrics:
    - outputs/results.json:
        cache: false
  inference:
    cmd: python inference.py
    deps:
    - data/test.csv
    - inference.py
    - outputs/checkpoint.pth
    - outputs/config.json
    - outputs/vocab.plk
    outs:
    - outputs/submission.csv
