stages:
  build:
    cmd: export VOCAB_PATH=outputs/vocab.plk MODEL_PATH=outputs/checkpoint.pth CONFIG_PATH=outputs/config.json
      RESULTS_PATH=outputs/results.json SUBMISSION_PATH=outputs/submission.csv
    always_changed: true
  prepare:
    cmd: python -m scripts.prepare
    deps:
    - scripts/prepare.py
    - data/train.csv
    params:
    - basic
    outs:
    - outputs/vocab.plk
  train:
    foreach: # List of simple values
    - mlp
    - lstm
    - selected
    do:
      cmd: python -m scripts.train ${item}
      deps:
      - data/train.csv
      - outputs/vocab.plk
      - scripts/train.py
      params:
      - ${item}
      metrics:
      - outputs/${item}_results.json:
          cache: false
      outs:
      - outputs/${item}_checkpoint.pth
      - outputs/${item}_config.json
  inference:
    foreach: # List of simple values
    - mlp
    - lstm
    - selected
    do:
      cmd: python -m scripts.inference_${item}
      deps:
      - data/test.csv
      - scripts/inference_${item}.py
      - outputs/${item}_checkpoint.pth
      - outputs/${item}_config.json
      outs:
      - outputs/${item}_submission.csv
