stages:
  prepare:
    cmd: python -m scripts.prepare
    deps:
    - scripts/prepare.py
    - data/train.csv
    params:
    - basic
    outs:
    - outputs/vocab.plk
  validate:
    foreach: # List of simple values
      - mlp
      - lstm
      - cnn
      - selected
    do:
      cmd: python -m scripts.validate ${item}
      deps:
        - data/train.csv
        - outputs/vocab.plk
        - outputs/config.json
        - scripts/validate.py
      params:
        - ${item}
        - validate
      metrics:
        - outputs/${item}_validate_results.json:
            cache: false
      plots:
        - outputs/${item}_validate_plots.csv:
            cache: false
  validate_bert:
    foreach: # List of simple values
      - basic
    do:
      cmd: python -m scripts.validate_bert ${item}
      deps:
        - data/train.csv
        - scripts/validate_bert.py
      params:
        - bert.max_len
        - bert.${item}
        - validate
      metrics:
        - outputs/bert-${item}_validate_results.json:
            cache: false
      plots:
        - outputs/bert-${item}_validate_plots.csv:
            cache: false
  train:
    foreach: # List of simple values
    - mlp
    - lstm
    - cnn
    - selected
    do:
      cmd: python -m scripts.train ${item}
      deps:
      - data/train.csv
      - outputs/vocab.plk
      - outputs/config.json
      - scripts/train.py
      params:
      - ${item}
      - train
      metrics:
      - outputs/${item}_results.json:
          cache: false
      plots:
      - outputs/${item}_plots.csv:
          cache: false
      outs:
      - outputs/${item}_checkpoint.pth
  inference:
    foreach: # List of simple values
    - mlp
    - lstm
    - cnn
    - selected
    do:
      cmd: python -m scripts.inference ${item}
      deps:
      - data/test.csv
      - scripts/inference.py
      - outputs/${item}_checkpoint.pth
      - outputs/config.json
      outs:
      - outputs/${item}_submission.csv
