stages:
  prepare:
    cmd: python -m scripts.prepare
    deps:
    - scripts/prepare.py
    - data/train.csv
    params:
    - basic
    outs:
    - outputs/vocab.plk
  validate:
    foreach: # List of simple values
      - mlp
      - lstm
      - cnn
      - selected
    do:
      cmd: python -m scripts.validate ${item}
      deps:
        - data/train.csv
        - outputs/vocab.plk
        - outputs/config.json
        - scripts/validate.py
      params:
        - ${item}
        - validate
      metrics:
        - outputs/${item}_validate_results.json:
            cache: false
      plots:
        - outputs/${item}_validate_plots.csv:
            cache: false

  validate_bert:
    foreach: # List of simple values
      bert-base-uncased_basic:
        pretrained_model: bert-base-uncased
        method: basic
      bert-base-uncased_lstm:
        pretrained_model: bert-base-uncased
        method: lstm
      bert-large-uncased_basic:
        pretrained_model: bert-large-uncased
        method: basic
      bert-large-uncased_lstm:
        pretrained_model: bert-large-uncased
        method: lstm
    do:
      cmd: python -m scripts.validate_bert bert ${item.pretrained_model} ${item.method}
      deps:
        - data/train.csv
        - model/bert/${item.method}.py
        - scripts/validate_bert.py
      params:
        - bert.max_len
        - bert.do_lower_case
        - bert.${item.method}
        - validate
      metrics:
        - outputs/bert-${item.pretrained_model}-${item.method}_validate_results.json:
            cache: false
      plots:
        - outputs/bert-${item.pretrained_model}-${item.method}_validate_plots.csv:
            cache: false

  validate_xlnet:
    foreach: # List of simple values
      - basic
      - sequence_classification
    do:
      cmd: python -m scripts.validate_bert xlnet ${item}
      deps:
        - data/train.csv
        - model/xlnet/${item}.py
        - scripts/validate_bert.py
      params:
        - xlnet.max_len
        - xlnet.${item}
        - xlnet.pretrained_model
        - validate
      metrics:
        - outputs/xlnet-${item}_validate_results.json:
            cache: false
      plots:
        - outputs/xlnet-${item}_validate_plots.csv:
            cache: false

  validate_roberta:
    foreach: # List of simple values
      siebert/sentiment-roberta-large-english_sentiment:
        pretrained_model: siebert/sentiment-roberta-large-english
        method: sentiment
    do:
      cmd: python -m scripts.validate_bert roberta ${item.pretrained_model} ${item.method}
      deps:
        - data/train.csv
        - model/roberta/${item.method}.py
        - scripts/validate_bert.py
      params:
        - roberta.max_len
        - roberta.do_lower_case
        - roberta.${item.method}
        - validate
      metrics:
        - outputs/roberta-${item.pretrained_model}-${item.method}_validate_results.json:
            cache: false
      plots:
        - outputs/roberta-${item.pretrained_model}-${item.method}_validate_plots.csv:
            cache: false

  train:
    foreach: # List of simple values
    - mlp
    - lstm
    - cnn
    - selected
    do:
      cmd: python -m scripts.train ${item}
      deps:
      - data/train.csv
      - outputs/vocab.plk
      - outputs/config.json
      - scripts/train.py
      params:
      - ${item}
      - train
      metrics:
      - outputs/${item}_results.json:
          cache: false
      plots:
      - outputs/${item}_plots.csv:
          cache: false
      outs:
      - outputs/${item}_checkpoint.pth

  train_bert:
    foreach: # List of simple values
      - basic
      - lstm
    do:
      cmd: python -m scripts.train_bert bert ${item}
      deps:
      - data/train.csv
      - scripts/train_bert.py
      params:
      - bert.max_len
      - bert.${item}
      - bert.pretrained_model
      - train
      metrics:
        - outputs/bert-${item}_results.json:
            cache: false
      plots:
        - outputs/bert-${item}_plots.csv:
            cache: false
      outs:
        - outputs/bert-${item}_checkpoint.pth

  inference:
    foreach: # List of simple values
    - mlp
    - lstm
    - cnn
    - selected
    do:
      cmd: python -m scripts.inference ${item}
      deps:
      - data/test.csv
      - scripts/inference.py
      - outputs/${item}_checkpoint.pth
      - outputs/config.json
      outs:
      - outputs/${item}_submission.csv

  inference_bert:
    foreach: # List of simple values
      - basic
      - lstm
    do:
      cmd: python -m scripts.inference_bert bert ${item}
      deps:
        - data/test.csv
        - scripts/inference_bert.py
        - outputs/bert-${item}_checkpoint.pth
      outs:
        - outputs/bert-${item}_submission.csv
