stages:
  prepare:
    cmd: python -m scripts.prepare
    deps:
    - scripts/prepare.py
    - data/train.csv
    params:
    - basic
    outs:
    - outputs/vocab.plk
  train:
    foreach: # List of simple values
    - mlp
    - lstm
    - selected
    do:
      cmd: python -m scripts.train ${item}
      deps:
      - data/train.csv
      - outputs/vocab.plk
      - outputs/config.json
      - scripts/train.py
      params:
      - ${item}
      - train
      metrics:
      - outputs/${item}_results.json:
          cache: false
      plots:
      - outputs/${item}_plots.csv:
          cache: false
      outs:
      - outputs/${item}_checkpoint.pth
  inference:
    foreach: # List of simple values
    - mlp
    - lstm
    - selected
    do:
      cmd: python -m scripts.inference ${item}
      deps:
      - data/test.csv
      - scripts/inference.py
      - outputs/${item}_checkpoint.pth
      - outputs/config.json
      outs:
      - outputs/${item}_submission.csv
