seed: 123
gpu: 0
log_interval: 500

feature: review
label: sentiment
pad_token: "<pad>"
unk_token: "<unk>"

basic:
  vocab_size: 30000
  min_freq: 3

model:
  arch: "mlp"
  embed_dim: 50
  sent_len: 256

train:
  batch_size: 64
  shuffle: true
  epochs: 10
  kfold: 10
  optimizer:
    lr: 0.01
    step_lr: 1.0
    gamma: 0.1
    clip: 0.1
