seed: 123
gpu: 0
log_interval: 500

feature: review
label: sentiment
pad_token: <pad>
unk_token: <unk>
sos_token: <sos>
eos_token: <eos>
max_len: 512

basic:
  vocab_size: 30000
  min_freq: 3

lstm:
  embed_dim: 128
  use_bag: false
  use_eos: true
  attention_method: concat
  hidden_size: 512
  n_layers: 2
  dropout: 0.33
  max_len: 512

mlp:
  embed_dim: 50
  use_bag: true
  hidden_size: 512
  dropout: 0.1

cnn:
  embed_dim: 128
  use_bag: false
  use_eos: true
  hidden_size: 512
  kernel_size: 3
  n_layers: 4
  dropout: 0.33
  max_len: 512


selected:
  embed_size: 50
  use_bag: false
  attention_method: concat
  hidden_size: 512
  n_layers: 2
  dropout: 0.33

train:
  batch_size: 32
  shuffle: true
  epochs: 4
  optimizer:
    lr: 2e-5
    step_lr: 2.0
    gamma: 0.5
    clip: 1.0
    weight_decay: 0

validate:
  batch_size: 32
  shuffle: true
  epochs: 4
  kfold: 10
  early_stops: 3
  optimizer:
    lr: 2e-5
    step_lr: 2.0
    gamma: 0.5
    clip: 1.0
    weight_decay: 0

evaluate:
  batch_size: 64

bert:
  do_lower_case: true
  max_len: 128
  eval_max_len: 512
  bert_hidden_size: 768
  basic:
    dropout: 0.1
  lstm:
    hidden_size: 512
    dropout: 0.1
    n_layers: 2
    attention_method: concat


xlnet:
  max_len: 128
  eval_max_len: 512
  pretrained_model: xlnet-base-cased
  bert_hidden_size: 768
  basic:
    dropout: 0.1
  sequence_classification:
    dropout: 0.1
  lstm:
    hidden_size: 512
    dropout: 0.1
    n_layers: 2
    attention_method: concat
