seed: 123
gpu: 0
log_interval: 500

feature: review
label: sentiment
pad_token: <pad>
unk_token: <unk>
sos_token: <sos>
eos_token: <eos>

basic:
  vocab_size: 30000
  min_freq: 3

lstm:
  embed_dim: 128
  use_bag: false
  use_eos: true
  attention_method: concat
  hidden_size: 512
  n_layers: 2
  dropout: 0.33
  max_len: 512

mlp:
  embed_dim: 50
  use_bag: true
  hidden_size: 512
  dropout: 0.1

cnn:
  embed_dim: 50
  use_bag: false
  hidden_size: 512
  kernel_size: 3


selected:
  embed_dim: 50
  use_bag: false
  attention_method: concat
  hidden_size: 512
  n_layers: 2
  dropout: 0.33

train:
  batch_size: 32
  shuffle: true
  epochs: 3
  kfold: 5
  optimizer:
    lr: 0.01
    step_lr: 1.0
    gamma: 0.5
    clip: 1.0

evaluate:
  batch_size: 200
